---
- when: ansible_distribution in ['Debian', 'Ubuntu'] 
  import_tasks: apt.yml

- when: ansible_distribution in ['RedHat','CentOS'] 
  import_tasks: rpm.yml

- when: ansible_distribution in ['Alpine']
  import_tasks: apk.yml
  
- name: Sync configuration
  copy: force=yes backup=no src=torrc dest=/etc/tor/torrc

- name: Start tor service
  service: name=tor state=started

- name: Display hidden service name
  debug: "Node address: {{ lookup('file', '/var/lib/tor/hidden_service/hostname') }}"

# vim:ft=ansible:sts=4:ts=4:et:cin:ai:sw=4:
